spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/chanel_rest
    username : postgres
    password : 1234
    driver : org.postgresql.Driver
  jpa:
    show-sql : true
  liquibase:
    enabled: true
    contexts: dev